modLoader="javafml"
loaderVersion="[47,)"
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/HellFirePvP/ObserverLib/issues"
[[mods]]
modId="observerlib"
version="${file.jarVersion}"
displayName="ObserverLib"
displayURL="https://www.curseforge.com/minecraft/mc-mods/observerlib"
logoFile="logo.png"
authors="HellFirePvP"
description='''Cached world structure and change monitoring library.'''
[[dependencies.observerlib]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.observerlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
