package hellfirepvp.astralsorcery.common.registry;

import net.minecraft.world.level.effect.MobEffect;
import net.minecraft.world.item.enchantment.Enchantment;
import hellfirepvp.astralsorcery.common.perk.type.PerkAttributeType;
import hellfirepvp.astralsorcery.AstralSorcery;
import hellfirepvp.astralsorcery.common.lib.EnchantmentsAS;
import hellfirepvp.astralsorcery.common.lib.EngravingEffectsAS;
import net.minecraft.world.item.enchantment.EnchantmentCategory;
import hellfirepvp.astralsorcery.common.perk.type.ModifierType;
import hellfirepvp.astralsorcery.common.lib.PerkAttributeTypesAS;
import net.minecraft.world.item.enchantment.Enchantments;
import hellfirepvp.astralsorcery.common.constellation.engraving.EngravingEffect;
import net.minecraft.world.level.effect.MobEffects;
import hellfirepvp.astralsorcery.common.constellation.IConstellation;
import hellfirepvp.astralsorcery.common.lib.ConstellationsAS;

public class RegistryEngravingEffects
{
    private RegistryEngravingEffects() {
    }
    
    public static void init() {
        EngravingEffectsAS.AEVITAS = newEffect(ConstellationsAS.aevitas).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76428_l, 0, 3)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_185296_A, 1, 1)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_HEALTH, ModifierType.ADDITION, 1.0f, 3.0f).addApplicableType(EnchantmentCategory.WEARABLE).formatResultAsInteger()).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_ATTACK_LIFE_LEECH, ModifierType.ADDITION, 2.0f, 4.0f).addApplicableType(EnchantmentCategory.WEAPON).addApplicableType(EnchantmentCategory.BOW).addApplicableType(EnchantmentCategory.CROSSBOW).addApplicableType(EnchantmentCategory.TRIDENT).formatResultAsInteger());
        EngravingEffectsAS.ARMARA = newEffect(ConstellationsAS.armara).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76429_m, 0, 0)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_180310_c, 2, 5)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_ARMOR, ModifierType.STACKING_MULTIPLY, 1.05f, 1.1f).addApplicableType(EnchantmentCategory.WEARABLE)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_INC_DODGE, ModifierType.ADDITION, 5.0f, 10.0f).addApplicableType(EnchantmentCategory.WEAPON).addApplicableType(EnchantmentCategory.BOW).addApplicableType(EnchantmentCategory.CROSSBOW).addApplicableType(EnchantmentCategory.TRIDENT).formatResultAsInteger());
        EngravingEffectsAS.DISCIDIA = newEffect(ConstellationsAS.discidia).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76420_g, 0, 3)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_185302_k, 3, 7)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_185309_u, 3, 7)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_203196_F, 1, 1).setIgnoreCompatibility()).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_INC_CRIT_CHANCE, ModifierType.ADDITION, 3.0f, 6.0f).addApplicableType(EnchantmentCategory.WEARABLE)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_MELEE_DAMAGE, ModifierType.STACKING_MULTIPLY, 1.05f, 1.2f).addApplicableType(EnchantmentCategory.WEAPON)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_PROJ_DAMAGE, ModifierType.STACKING_MULTIPLY, 1.05f, 1.2f).addApplicableType(EnchantmentCategory.BOW).addApplicableType(EnchantmentCategory.CROSSBOW));
        EngravingEffectsAS.EVORSIO = newEffect(ConstellationsAS.evorsio).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76422_e, 1, 3)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.ALL_DAMAGE_PROTECTION, 3, 6)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_INC_HARVEST_SPEED, ModifierType.ADDED_MULTIPLY, 0.1f, 0.25f).addApplicableType(EnchantmentCategory.DIGGER));
        EngravingEffectsAS.VICIO = newEffect(ConstellationsAS.vicio).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76424_c, 1, 3)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_180309_e, 1, 4)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_203195_E, 1, 5)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_ATTACK_SPEED, ModifierType.ADDED_MULTIPLY, 0.15f, 0.25f).addApplicableType(EnchantmentCategory.WEAPON).addApplicableType(EnchantmentCategory.DIGGER).addApplicableType(EnchantmentCategory.BOW).addApplicableType(EnchantmentCategory.CROSSBOW).addApplicableType(EnchantmentCategory.TRIDENT)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_MOVESPEED, ModifierType.STACKING_MULTIPLY, 1.05f, 1.1f).addApplicableType(EnchantmentCategory.ARMOR_FEET));
        EngravingEffectsAS.BOOTES = newEffect(ConstellationsAS.bootes).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76443_y, 1, 5)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.SILK_TOUCH, 1, 1)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_203193_C, 2, 4)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_HEALTH, ModifierType.ADDITION, 1.0f, 2.0f).addApplicableType(EnchantmentCategory.WEARABLE).formatResultAsInteger()).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_REACH, ModifierType.ADDED_MULTIPLY, 0.05f, 0.1f).addApplicableType(EnchantmentCategory.DIGGER).addApplicableType(EnchantmentCategory.WEAPON).addApplicableType(EnchantmentCategory.TRIDENT));
        EngravingEffectsAS.FORNAX = newEffect(ConstellationsAS.fornax).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76426_n, 0, 0)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_77334_n, 1, 3)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.SHARPNESS, 1, 2)).addEffect(new EngravingEffect.EnchantmentEffect(() -> EnchantmentsAS.SCORCHING_HEAT, 1, 1)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_INC_CRIT_CHANCE, ModifierType.ADDED_MULTIPLY, 0.1f, 0.2f).addApplicableType(EnchantmentCategory.WEAPON).addApplicableType(EnchantmentCategory.BOW).addApplicableType(EnchantmentCategory.CROSSBOW).addApplicableType(EnchantmentCategory.TRIDENT)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_INC_CRIT_MULTIPLIER, ModifierType.ADDED_MULTIPLY, 0.1f, 0.2f).addApplicableType(EnchantmentCategory.WEARABLE));
        EngravingEffectsAS.HOROLOGIUM = newEffect(ConstellationsAS.horologium).addEffect(new EngravingEffect.PotionEffect(() -> MobEffects.LEVITATION, 3, 5)).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76424_c, 1, 2)).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76422_e, 2, 3)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.BLOCK_FORTUNE, 4, 6)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_185304_p, 3, 6)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_COOLDOWN_REDUCTION, ModifierType.ADDED_MULTIPLY, 0.1f, 0.2f).addApplicableType(EnchantmentCategory.DIGGER).addApplicableType(EnchantmentCategory.TRIDENT).addApplicableType(EnchantmentCategory.BOW).addApplicableType(EnchantmentCategory.CROSSBOW).addApplicableType(EnchantmentCategory.FISHING_ROD).addApplicableType(EnchantmentCategory.WEAPON)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_INC_PERK_EXP, ModifierType.STACKING_MULTIPLY, 1.1f, 1.2f).addApplicableType(EnchantmentCategory.ARMOR_HEAD)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_INC_PERK_EFFECT, ModifierType.STACKING_MULTIPLY, 1.04f, 1.08f).addApplicableType(EnchantmentCategory.ARMOR_FEET).addApplicableType(EnchantmentCategory.ARMOR_CHEST).addApplicableType(EnchantmentCategory.ARMOR_LEGS));
        EngravingEffectsAS.LUCERNA = newEffect(ConstellationsAS.lucerna).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76439_r, 0, 0)).addEffect(new EngravingEffect.EnchantmentEffect(() -> EnchantmentsAS.NIGHT_VISION, 1, 1)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_ALIGNMENT_CHARGE_MAXIMUM, ModifierType.ADDED_MULTIPLY, 0.15f, 0.3f).addApplicableType(EnchantmentCategory.WEARABLE)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_ALIGNMENT_CHARGE_REGENERATION, ModifierType.STACKING_MULTIPLY, 1.2f, 1.3f).addApplicableType(EnchantmentCategory.DIGGER).addApplicableType(EnchantmentCategory.WEAPON).addApplicableType(EnchantmentCategory.BOW).addApplicableType(EnchantmentCategory.CROSSBOW).addApplicableType(EnchantmentCategory.TRIDENT));
        EngravingEffectsAS.MINERALIS = newEffect(ConstellationsAS.mineralis).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76422_e, 0, 2)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.BLOCK_FORTUNE, 1, 3)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_INC_HARVEST_SPEED, ModifierType.ADDED_MULTIPLY, 0.1f, 0.2f).addApplicableType(EnchantmentCategory.WEARABLE)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_MINING_SIZE, ModifierType.ADDITION, 1.0f, 1.0f).addApplicableType(EnchantmentCategory.DIGGER).formatResultAsInteger());
        EngravingEffectsAS.OCTANS = newEffect(ConstellationsAS.octans).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76427_o, 1, 3)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_185298_f, 2, 4)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_SWIMSPEED, ModifierType.ADDED_MULTIPLY, 0.05f, 0.08f).addApplicableType(EnchantmentCategory.WEARABLE));
        EngravingEffectsAS.PELOTRIO = newEffect(ConstellationsAS.pelotrio).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76444_x, 1, 4)).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76428_l, 2, 4)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_151369_A, 3, 5)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.SMITE, 1, 1)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_POTION_DURATION, ModifierType.ADDED_MULTIPLY, 0.15f, 0.2f).addApplicableType(EnchantmentCategory.WEARABLE)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_INC_DODGE, ModifierType.ADDED_MULTIPLY, 0.05f, 0.15f).addApplicableType(EnchantmentCategory.WEARABLE));
        EngravingEffectsAS.ALCARA = newEffect(ConstellationsAS.alcara).addEffect(new EngravingEffect.PotionEffect(() -> MobEffects.LEVITATION, 3, 6)).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76441_p, 0, 1)).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76424_c, 1, 2)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_191530_r, 3, 6)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_151369_A, 2, 5).setIgnoreCompatibility()).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_151370_z, 3, 6).setIgnoreCompatibility()).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.SILK_TOUCH, 1, 1)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_222193_H, 1, 4)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_RAMPAGE_DURATION, ModifierType.STACKING_MULTIPLY, 1.15f, 1.3f).addApplicableType(EnchantmentCategory.WEARABLE)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_BLEED_CHANCE, ModifierType.STACKING_MULTIPLY, 1.2f, 1.4f).addApplicableType(EnchantmentCategory.WEAPON).addApplicableType(EnchantmentCategory.TRIDENT)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_PROJ_SPEED, ModifierType.STACKING_MULTIPLY, 1.25f, 1.5f).addApplicableType(EnchantmentCategory.BOW).addApplicableType(EnchantmentCategory.CROSSBOW));
        EngravingEffectsAS.GELU = newEffect(ConstellationsAS.gelu).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76429_m, 1, 2)).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76426_n, 0, 0)).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76421_d, 0, 1)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_185301_j, 1, 1)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_180309_e, 1, 1)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.FIRE_PROTECTION, 2, 4)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_INC_ENCH_EFFECT, ModifierType.ADDED_MULTIPLY, 0.05f, 0.1f).addApplicableType(EnchantmentCategory.WEARABLE)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_REACH, ModifierType.ADDITION, 1.0f, 2.0f).addApplicableType(EnchantmentCategory.DIGGER).formatResultAsInteger()).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_INC_CRIT_MULTIPLIER, ModifierType.STACKING_MULTIPLY, 1.1f, 1.2f).addApplicableType(EnchantmentCategory.WEAPON).addApplicableType(EnchantmentCategory.TRIDENT).addApplicableType(EnchantmentCategory.BOW).addApplicableType(EnchantmentCategory.CROSSBOW));
        EngravingEffectsAS.ULTERIA = newEffect(ConstellationsAS.ulteria).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76444_x, 0, 4)).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76428_l, 1, 3)).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76437_t, 1, 2)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.FIRE_PROTECTION, 2, 3).setIgnoreCompatibility()).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_77329_d, 4, 6).setIgnoreCompatibility()).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_185297_d, 4, 6).setIgnoreCompatibility()).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_180308_g, 4, 6).setIgnoreCompatibility()).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_222192_G, 1, 1)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_INC_ALL_ELEMENTAL_RESIST, ModifierType.ADDED_MULTIPLY, 0.05f, 0.15f).addApplicableType(EnchantmentCategory.WEARABLE)).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_INC_THORNS, ModifierType.ADDITION, 10.0f, 20.0f).addApplicableType(EnchantmentCategory.WEAPON).addApplicableType(EnchantmentCategory.TRIDENT).formatResultAsInteger()).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_INC_DODGE, ModifierType.ADDITION, 10.0f, 20.0f).addApplicableType(EnchantmentCategory.BOW).addApplicableType(EnchantmentCategory.CROSSBOW).formatResultAsInteger());
        EngravingEffectsAS.VORUX = newEffect(ConstellationsAS.vorux).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76420_g, 2, 3)).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76429_m, 0, 1)).addEffect(new EngravingEffect.PotionEffect(() -> Effects.field_76419_f, 1, 3)).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_185303_l, 4, 7).setIgnoreCompatibility()).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_180312_n, 4, 7).setIgnoreCompatibility()).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_185302_k, 3, 4).setIgnoreCompatibility()).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_185309_u, 3, 4).setIgnoreCompatibility()).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_203196_F, 3, 4).setIgnoreCompatibility()).addEffect(new EngravingEffect.EnchantmentEffect(() -> Enchantments.field_222194_I, 3, 6).setIgnoreCompatibility()).addEffect(new EngravingEffect.ModifierEffect(() -> PerkAttributeTypesAS.ATTR_TYPE_MOVESPEED, ModifierType.ADDED_MULTIPLY, 0.05f, 0.1f).addApplicableType(EnchantmentCategory.WEARABLE));
    }
    
    private static EngravingEffect newEffect(final IConstellation cst) {
        return register(new EngravingEffect(cst));
    }
    
    private static <T extends EngravingEffect> T register(final T effect) {
        AstralSorcery.getProxy().getRegistryPrimer().register(effect);
        return effect;
    }
}
