package hellfirepvp.astralsorcery.common.lib;

import java.awt.Color;

public class ColorsAS
{
    public static final Color DEFAULT_GENERIC_PARTICLE;
    public static final Color ROCK_CRYSTAL;
    public static final Color CELESTIAL_CRYSTAL;
    public static final Color EFFECT_LIGHTNING;
    public static final Color EFFECT_CRAFT_FLARE;
    public static final Color EFFECT_BLUE_LIGHT;
    public static final Color EFFECT_BLUE_DARK;
    public static final Color EFFECT_PROXIMITY_LIGHTNING;
    public static final Color OVERLAY_CHARGE_MISSING;
    public static final Color OVERLAY_CHARGE_USAGE;
    public static final Color MANTLE_ARMARA_STACKS;
    public static final Color MANTLE_LUCERNA_SPAWNER;
    public static final Color MANTLE_LUCERNA_INVENTORY;
    public static final Color GEM_SKY;
    public static final Color GEM_DAY;
    public static final Color GEM_NIGHT;
    public static final Color NOCTURNAL_POWDER_1;
    public static final Color NOCTURNAL_POWDER_2;
    public static final Color NOCTURNAL_POWDER_3;
    public static final Color ILLUMINATION_POWDER_1;
    public static final Color ILLUMINATION_POWDER_2;
    public static final Color ILLUMINATION_POWDER_3;
    public static final Color SPECTRAL_TOOL;
    public static final Color RESONATOR_STARFIELD;
    public static final Color CONSTELLATION_TYPE_MAJOR;
    public static final Color CONSTELLATION_TYPE_WEAK;
    public static final Color CONSTELLATION_TYPE_MINOR;
    public static final Color CONSTELLATION_TYPE_BLANK;
    public static final Color CONSTELLATION_SINGLE_STAR;
    public static final Color PERK_CONNECTION_UNALLOCATED;
    public static final Color PERK_CONNECTION_ALLOCATED;
    public static final Color PERK_CONNECTION_UNLOCKABLE;
    public static final Color PERK_UNALLOCATED;
    public static final Color PERK_ALLOCATED;
    public static final Color PERK_UNLOCKABLE;
    public static final Color EFFECT_BLEED;
    public static final Color EFFECT_CHEAT_DEATH;
    public static final Color EFFECT_DROP_MODIFIER;
    public static final Color EFFECT_TIME_FREEZE;
    public static final Color COLORED_LENS_FIRE;
    public static final Color COLORED_LENS_BREAK;
    public static final Color COLORED_LENS_GROWTH;
    public static final Color COLORED_LENS_DAMAGE;
    public static final Color COLORED_LENS_REGEN;
    public static final Color COLORED_LENS_PUSH;
    public static final Color COLORED_LENS_SPECTRAL;
    public static final Color RITUAL_CONSTELLATION_AEVITAS;
    public static final Color RITUAL_CONSTELLATION_ARMARA;
    public static final Color RITUAL_CONSTELLATION_ARMARA_SECONDARY;
    public static final Color RITUAL_CONSTELLATION_LUCERNA;
    public static final Color RITUAL_CONSTELLATION_VICIO;
    public static final Color CONSTELLATION_DISCIDIA;
    public static final Color CONSTELLATION_ARMARA;
    public static final Color CONSTELLATION_VICIO;
    public static final Color CONSTELLATION_AEVITAS;
    public static final Color CONSTELLATION_EVORSIO;
    public static final Color CONSTELLATION_LUCERNA;
    public static final Color CONSTELLATION_MINERALIS;
    public static final Color CONSTELLATION_HOROLOGIUM;
    public static final Color CONSTELLATION_OCTANS;
    public static final Color CONSTELLATION_BOOTES;
    public static final Color CONSTELLATION_FORNAX;
    public static final Color CONSTELLATION_PELOTRIO;
    public static final Color CONSTELLATION_GELU;
    public static final Color CONSTELLATION_ULTERIA;
    public static final Color CONSTELLATION_ALCARA;
    public static final Color CONSTELLATION_VORUX;
    public static final Color REFRACTION_TABLE_R1_RED;
    public static final Color REFRACTION_TABLE_R1_YELLOW;
    public static final Color REFRACTION_TABLE_R1_GREEN;
    public static final Color REFRACTION_TABLE_R1_TURQUOISE;
    public static final Color REFRACTION_TABLE_R1_BLUE;
    public static final Color REFRACTION_TABLE_R1_PINK;
    public static final Color REFRACTION_TABLE_R2_ORANGE;
    public static final Color REFRACTION_TABLE_R2_YELLOW;
    public static final Color REFRACTION_TABLE_R2_GREEN;
    public static final Color REFRACTION_TABLE_R2_BLUE;
    public static final Color REFRACTION_TABLE_R2_DARK_BLUE;
    public static final Color REFRACTION_TABLE_R2_PINK;
    public static final Color[] REFRACTION_TABLE_COLORS;
    public static final Color DYE_WHITE;
    public static final Color DYE_ORANGE;
    public static final Color DYE_MAGENTA;
    public static final Color DYE_LIGHT_BLUE;
    public static final Color DYE_YELLOW;
    public static final Color DYE_LIME;
    public static final Color DYE_PINK;
    public static final Color DYE_GRAY;
    public static final Color DYE_LIGHT_GRAY;
    public static final Color DYE_CYAN;
    public static final Color DYE_PURPLE;
    public static final Color DYE_BLUE;
    public static final Color DYE_BROWN;
    public static final Color DYE_GREEN;
    public static final Color DYE_RED;
    public static final Color DYE_BLACK;
    public static final Color[] DYE_COLOR_PARTICLES;
    
    private ColorsAS() {
    }
    
    static {
        DEFAULT_GENERIC_PARTICLE = new Color(60, 0, 255);
        ROCK_CRYSTAL = new Color(14540287);
        CELESTIAL_CRYSTAL = new Color(35071);
        EFFECT_LIGHTNING = new Color(103935);
        EFFECT_CRAFT_FLARE = new Color(5269228);
        EFFECT_BLUE_LIGHT = new Color(6133976);
        EFFECT_BLUE_DARK = new Color(23230);
        EFFECT_PROXIMITY_LIGHTNING = new Color(11731972);
        OVERLAY_CHARGE_MISSING = new Color(10619136);
        OVERLAY_CHARGE_USAGE = new Color(47363);
        MANTLE_ARMARA_STACKS = new Color(7368447);
        MANTLE_LUCERNA_SPAWNER = new Color(10223872);
        MANTLE_LUCERNA_INVENTORY = new Color(43267);
        GEM_SKY = new Color(2449845);
        GEM_DAY = new Color(14699522);
        GEM_NIGHT = new Color(8421504);
        NOCTURNAL_POWDER_1 = Color.BLACK;
        NOCTURNAL_POWDER_2 = new Color(5112173);
        NOCTURNAL_POWDER_3 = new Color(791926);
        ILLUMINATION_POWDER_1 = Color.WHITE;
        ILLUMINATION_POWDER_2 = new Color(16711582);
        ILLUMINATION_POWDER_3 = new Color(16770361);
        SPECTRAL_TOOL = new Color(6041324);
        RESONATOR_STARFIELD = new Color(1594);
        CONSTELLATION_TYPE_MAJOR = new Color(40, 67, 204);
        CONSTELLATION_TYPE_WEAK = new Color(67, 44, 176);
        CONSTELLATION_TYPE_MINOR = new Color(93, 25, 127);
        CONSTELLATION_TYPE_BLANK = new Color(-865704346);
        CONSTELLATION_SINGLE_STAR = new Color(15777024);
        PERK_CONNECTION_UNALLOCATED = new Color(12303359);
        PERK_CONNECTION_ALLOCATED = new Color(15658496);
        PERK_CONNECTION_UNLOCKABLE = new Color(29183);
        PERK_UNALLOCATED = new Color(3355647);
        PERK_ALLOCATED = new Color(15658496);
        PERK_UNLOCKABLE = new Color(13181149);
        EFFECT_BLEED = new Color(7672320);
        EFFECT_CHEAT_DEATH = new Color(16733969);
        EFFECT_DROP_MODIFIER = new Color(16765204);
        EFFECT_TIME_FREEZE = new Color(6908265);
        COLORED_LENS_FIRE = new Color(16744192);
        COLORED_LENS_BREAK = new Color(16768768);
        COLORED_LENS_GROWTH = new Color(57088);
        COLORED_LENS_DAMAGE = new Color(14614528);
        COLORED_LENS_REGEN = new Color(16744383);
        COLORED_LENS_PUSH = new Color(57343);
        COLORED_LENS_SPECTRAL = new Color(8323263);
        RITUAL_CONSTELLATION_AEVITAS = new Color(63, 255, 63);
        RITUAL_CONSTELLATION_ARMARA = new Color(201, 30, 0);
        RITUAL_CONSTELLATION_ARMARA_SECONDARY = new Color(80, 0, 150);
        RITUAL_CONSTELLATION_LUCERNA = new Color(255, 255, 127);
        RITUAL_CONSTELLATION_VICIO = new Color(200, 200, 255);
        CONSTELLATION_DISCIDIA = new Color(14686467);
        CONSTELLATION_ARMARA = new Color(12041144);
        CONSTELLATION_VICIO = new Color(48557);
        CONSTELLATION_AEVITAS = new Color(3073024);
        CONSTELLATION_EVORSIO = new Color(10486016);
        CONSTELLATION_LUCERNA = new Color(16770825);
        CONSTELLATION_MINERALIS = new Color(13335818);
        CONSTELLATION_HOROLOGIUM = new Color(8197812);
        CONSTELLATION_OCTANS = new Color(7368447);
        CONSTELLATION_BOOTES = new Color(13901014);
        CONSTELLATION_FORNAX = new Color(16731675);
        CONSTELLATION_PELOTRIO = new Color(15466603);
        CONSTELLATION_GELU = new Color(7703464);
        CONSTELLATION_ULTERIA = new Color(3437667);
        CONSTELLATION_ALCARA = new Color(8399186);
        CONSTELLATION_VORUX = new Color(11044894);
        REFRACTION_TABLE_R1_RED = new Color(16713728);
        REFRACTION_TABLE_R1_YELLOW = new Color(16763904);
        REFRACTION_TABLE_R1_GREEN = new Color(7339776);
        REFRACTION_TABLE_R1_TURQUOISE = new Color(64767);
        REFRACTION_TABLE_R1_BLUE = new Color(10495);
        REFRACTION_TABLE_R1_PINK = new Color(16711934);
        REFRACTION_TABLE_R2_ORANGE = new Color(15759360);
        REFRACTION_TABLE_R2_YELLOW = new Color(11857920);
        REFRACTION_TABLE_R2_GREEN = new Color(126976);
        REFRACTION_TABLE_R2_BLUE = new Color(31472);
        REFRACTION_TABLE_R2_DARK_BLUE = new Color(3735792);
        REFRACTION_TABLE_R2_PINK = new Color(15728763);
        REFRACTION_TABLE_COLORS = new Color[] { ColorsAS.REFRACTION_TABLE_R1_RED, ColorsAS.REFRACTION_TABLE_R1_YELLOW, ColorsAS.REFRACTION_TABLE_R1_GREEN, ColorsAS.REFRACTION_TABLE_R1_TURQUOISE, ColorsAS.REFRACTION_TABLE_R1_BLUE, ColorsAS.REFRACTION_TABLE_R1_PINK, ColorsAS.REFRACTION_TABLE_R2_ORANGE, ColorsAS.REFRACTION_TABLE_R2_YELLOW, ColorsAS.REFRACTION_TABLE_R2_GREEN, ColorsAS.REFRACTION_TABLE_R2_BLUE, ColorsAS.REFRACTION_TABLE_R2_DARK_BLUE, ColorsAS.REFRACTION_TABLE_R2_PINK };
        DYE_WHITE = new Color(16777215);
        DYE_ORANGE = new Color(16747549);
        DYE_MAGENTA = new Color(15666943);
        DYE_LIGHT_BLUE = new Color(452095);
        DYE_YELLOW = new Color(16771840);
        DYE_LIME = new Color(9699088);
        DYE_PINK = new Color(16718041);
        DYE_GRAY = new Color(6184542);
        DYE_LIGHT_GRAY = new Color(12434877);
        DYE_CYAN = new Color(5544116);
        DYE_PURPLE = new Color(12001783);
        DYE_BLUE = new Color(3932415);
        DYE_BROWN = new Color(12022025);
        DYE_GREEN = new Color(43520);
        DYE_RED = new Color(16711680);
        DYE_BLACK = new Color(0);
        DYE_COLOR_PARTICLES = new Color[] { ColorsAS.DYE_WHITE, ColorsAS.DYE_ORANGE, ColorsAS.DYE_MAGENTA, ColorsAS.DYE_LIGHT_BLUE, ColorsAS.DYE_YELLOW, ColorsAS.DYE_LIME, ColorsAS.DYE_PINK, ColorsAS.DYE_GRAY, ColorsAS.DYE_LIGHT_GRAY, ColorsAS.DYE_CYAN, ColorsAS.DYE_PURPLE, ColorsAS.DYE_BLUE, ColorsAS.DYE_BROWN, ColorsAS.DYE_GREEN, ColorsAS.DYE_RED, ColorsAS.DYE_BLACK };
    }
}
